org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Suppress strict AAR metadata checking for plugins targeting older compileSdk
android.dependency.suppressUnsupportedCompileSdk=androidx.fragment:fragment,androidx.window:window,androidx.window:window-java,androidx.activity:activity,androidx.lifecycle:lifecycle-livedata-core-ktx,androidx.lifecycle:lifecycle-livedata,androidx.lifecycle:lifecycle-viewmodel,androidx.lifecycle:lifecycle-livedata-core,androidx.lifecycle:lifecycle-viewmodel-savedstate,androidx.core:core-ktx,androidx.core:core,androidx.lifecycle:lifecycle-runtime,androidx.lifecycle:lifecycle-process,androidx.annotation:annotation-experimental,androidx.exifinterface:exifinterface
