[package]
name = "musializer-core"
version = "0.1.1"
edition = "2024"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
cpal = "0.18.2"
crossbeam-channel = "0.5.16"
rustfft = "6.4.1"
symphonia = { version = "0.5.4", features = ["all"] }
log = "0.4.34"
lazy_static = "1.5.0"
flutter_rust_bridge = "=2.13.0"

[target.'cfg(target_os = "android")'.dependencies]
ndk-context = "0.1"
jni = "0.22"

[features]
default = []
