name: mobile
description: "High-Performance GPU-Accelerated Audio Visualizer"
publish_to: 'none'

version: 0.1.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.13.0
  file_picker: ^12.1.2
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  flutter_quick_video_encoder: ^1.7.2
  wakelock_plus: ^1.7.0
  http: ^1.6.0
  package_info_plus: ^10.2.1
  url_launcher: ^6.3.2
  open_filex: ^4.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
