// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ENGINE`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `fmt`, `initialize`

Future<void> initEngine({required BigInt fftSize, required BigInt numBands}) =>
    RustLib.instance.api.crateApiInitEngine(
      fftSize: fftSize,
      numBands: numBands,
    );

Future<MobileTrackInfo> loadAudioFile({required String path}) =>
    RustLib.instance.api.crateApiLoadAudioFile(path: path);

Future<MobileTrackInfo> loadAudioBytes({
  required List<int> bytes,
  String? filenameHint,
}) => RustLib.instance.api.crateApiLoadAudioBytes(
  bytes: bytes,
  filenameHint: filenameHint,
);

Future<void> play() => RustLib.instance.api.crateApiPlay();

Future<void> pause() => RustLib.instance.api.crateApiPause();

Future<void> togglePlayPause() =>
    RustLib.instance.api.crateApiTogglePlayPause();

Future<void> seekSeconds({required double seconds}) =>
    RustLib.instance.api.crateApiSeekSeconds(seconds: seconds);

Future<void> setVolume({required double volume}) =>
    RustLib.instance.api.crateApiSetVolume(volume: volume);

Future<double> getVolume() => RustLib.instance.api.crateApiGetVolume();

Future<bool> isPlaying() => RustLib.instance.api.crateApiIsPlaying();

Future<double> currentTime() => RustLib.instance.api.crateApiCurrentTime();

Future<double> durationSeconds() =>
    RustLib.instance.api.crateApiDurationSeconds();

Future<void> setGainMultiplier({required double gain}) =>
    RustLib.instance.api.crateApiSetGainMultiplier(gain: gain);

Future<Float32List> getSpectrum({required double dt}) =>
    RustLib.instance.api.crateApiGetSpectrum(dt: dt);

class MobileTrackInfo {
  final String title;
  final double durationSeconds;
  final int sampleRate;
  final int channels;

  const MobileTrackInfo({
    required this.title,
    required this.durationSeconds,
    required this.sampleRate,
    required this.channels,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      durationSeconds.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileTrackInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          durationSeconds == other.durationSeconds &&
          sampleRate == other.sampleRate &&
          channels == other.channels;
}
